### ISSUE TITLE
SSLCertVerificationError when calling sessions_create

### ISSUE THREAD

**Issue by crodriguez01** [apideck-libraries/python-sdk#14]
Our app is using the following code to create a session:

```
api_instance = vault_api.VaultApi(api_client)
app_id = settings.API_DECK_APP_ID

session = Session(
    consumer_metadata=ConsumerMetadata(
        account_name=company.name,
        user_name=company.name,
    ),
)

response = api_instance.sessions_create(
    consumer_id=consumer_id, app_id=app_id, session=session
)
```
 When executing the sessions_create call we get the following error:

`urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='unify.apideck.com', port=443): Max retries exceeded with url: /vault/sessions (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)')))`

Any ideas on what could be the cause of this issue?

**Comment by thim81** [comment]
@elsmr or @GeertWille Does this issue ring a bell?

**Comment by crodriguez01** [comment]
The issue was fixed, thanks!
