### ISSUE TITLE
Unexpected error when retrieving opportunities from Hubspot CRM

### ISSUE THREAD

**Issue by enono78** [apideck-libraries/python-sdk#37]
We get the following exception when retrieving the Hubspot opportunities using the `CrmApi.opportunities_all` method:
```TypeError: _from_openapi_data() missing 1 required positional argument: 'primary_contact_id'```

**Comment by thim81** [comment]
hi @enono78 

We are about to release a new version of the SDKs which should improve the handling of nullable fields of strong-typed languages like Python.
This should also have a positive effect on the issue you are experiencing.

**Comment by thim81** [comment]
hi @enono78 

We released the new version of the SDK.

Can you confirm if the SDK error is gone now? 
After your feedback, we can close the issue or continue to investigate.

**Comment by budg** [comment]
hi @thim81 
I'm experiencing a similar issue when calling `api_instance.companies_all`:
`TypeError: Company._from_openapi_data() missing 1 required positional argument: 'name'`

We're using the latest version of your python-sdk (v1.1.2)

```python
      companies_sort = CompaniesSort(by="created_at", direction=SortDirection("desc"))
      companies = []

      with apideck.ApiClient(self.configuration) as api_client:
          api_instance = crm_api.CrmApi(api_client)

          async def get_batch(cursor=None):
              api_response = api_instance.companies_all(
                  consumer_id=self.consumer_id,
                  app_id=self.app_id,
                  service_id=self.service_id,
                  sort=companies_sort,
                  limit=200,
                  cursor=cursor,
              )
              for c in api_response.data:
                  companies.append(c)
              return api_response.meta.cursors.next

          next_cursor = await get_batch()
```

This only happens with some batches, others work fine. Can you recommend a solution?

**Comment by budg** [comment]
@thim81 do you have any ideas? Is there a bug fix planned? 
Thanks

**Comment by Gdewilde** [comment]
Hi @budg, thanks for the ping. We will look into this issue.
